<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1MVVLM6" failures="2" tests="4" name="Command line test" time="0.217" errors="0" timestamp="2024-04-25T23:00:16 WEST">
  <testcase classname="ap.MultipleCalculatorTest" name="testComputeWithInvalidX" time="0.029"/>
  <testcase classname="ap.MultipleCalculatorTest" name="testComputeWithInvalidY" time="0.001"/>
  <testcase classname="ap.MultipleCalculatorTest" name="testComputeWithNoMultiples" time="0.018">
    <failure type="java.lang.AssertionError" message="arrays don&amp;apos;t have the same size.  expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: arrays don't have the same size.  expected [1] but found [0]
at ap.MultipleCalculatorTest.testComputeWithNoMultiples(MultipleCalculatorTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 45 stack frames]]>
    </failure>
  </testcase> <!-- testComputeWithNoMultiples -->
  <testcase classname="ap.MultipleCalculatorTest" name="testComputeWithValidInput" time="0.0">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="Index 2 out of bounds for length 2">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at ap.MultipleCalculator.compute(MultipleCalculator.java:41)
at ap.MultipleCalculatorTest.testComputeWithValidInput(MultipleCalculatorTest.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testComputeWithValidInput -->
</testsuite> <!-- Command line test -->
